## 1. Import the NUMPY package under the name np.

In [2]:
import numpy as np

## 2. Print the NUMPY version and the configuration.

In [3]:
#your code here
print("The numpy's version is", np.__version__)
print(np.show_config())

The numpy's version is 1.17.3
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None


## 3. Generate a 2x3x5 
3-dimensional array with random values. 
Assign the array to variable "a"

Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [4]:
#your code here
a = np.random.random((2,3,5))

## 4. Print a.

In [5]:
#your code here
print(a)

[[[0.5059929  0.96234207 0.29135818 0.93129373 0.09923646]
  [0.91882161 0.80979227 0.35576494 0.51261907 0.21365027]
  [0.08451723 0.9586303  0.71160032 0.92298529 0.96094698]]

 [[0.88344735 0.90706979 0.33015663 0.98471268 0.02881393]
  [0.97152974 0.50688605 0.981655   0.86990314 0.2078938 ]
  [0.41048346 0.55964842 0.33277885 0.06417969 0.18998765]]]


## 5. Create a 5x2x3 
3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

In [6]:
#your code here
b = np.ones((5,2,3))

## 6. Print b.

In [7]:
#your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


## 7. Do a and b have the same size? How do you prove that in Python code?

In [8]:
#your code here
np.array_equal(a,b)

False

## 8. Are you able to add a and b? Why or why not?

In [9]:
#I can't add a and b because operands could not be broadcast together with shapes

## 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

In [10]:
#your code here
c = b.reshape(2,3,5)
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

## 10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

In [11]:
#your code here
d = np.add(a,c)
d

array([[[1.5059929 , 1.96234207, 1.29135818, 1.93129373, 1.09923646],
        [1.91882161, 1.80979227, 1.35576494, 1.51261907, 1.21365027],
        [1.08451723, 1.9586303 , 1.71160032, 1.92298529, 1.96094698]],

       [[1.88344735, 1.90706979, 1.33015663, 1.98471268, 1.02881393],
        [1.97152974, 1.50688605, 1.981655  , 1.86990314, 1.2078938 ],
        [1.41048346, 1.55964842, 1.33277885, 1.06417969, 1.18998765]]])

## 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

In [44]:
#your code here
print(a)
print(d)

[[[0.5059929  0.96234207 0.29135818 0.93129373 0.09923646]
  [0.91882161 0.80979227 0.35576494 0.51261907 0.21365027]
  [0.08451723 0.9586303  0.71160032 0.92298529 0.96094698]]

 [[0.88344735 0.90706979 0.33015663 0.98471268 0.02881393]
  [0.97152974 0.50688605 0.981655   0.86990314 0.2078938 ]
  [0.41048346 0.55964842 0.33277885 0.06417969 0.18998765]]]
[[[1.5059929  1.96234207 1.29135818 1.93129373 1.09923646]
  [1.91882161 1.80979227 1.35576494 1.51261907 1.21365027]
  [1.08451723 1.9586303  1.71160032 1.92298529 1.96094698]]

 [[1.88344735 1.90706979 1.33015663 1.98471268 1.02881393]
  [1.97152974 1.50688605 1.981655   1.86990314 1.2078938 ]
  [1.41048346 1.55964842 1.33277885 1.06417969 1.18998765]]]


## 12. Multiply a and c. Assign the result to e.

In [13]:
#your code here
#e = np.multiply(a,c)
e = a * c

## 13. Does e equal to a? Why or why not?

In [14]:
#your code here
np.array_equal(e,a)

True

## 14. Identify the max, min, and mean values in d. 
Assign those values to variables "d_max", "d_min", and "d_mean"

In [41]:
#your code here
d_max = np.max(a)
d_min = np.min(a)
d_mean = np.mean(a)
print(d_max)
print(d_min)
print(d_mean)

0.9847126759839266
0.028813925238303617
0.5822899270258068


## 15. Now we want to label the values in d. 
First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

In [49]:
#your code here
d=np.empty((2,3,5))
d

array([[[1.5059929 , 1.96234207, 1.29135818, 1.93129373, 1.09923646],
        [1.91882161, 1.80979227, 1.35576494, 1.51261907, 1.21365027],
        [1.08451723, 1.9586303 , 1.71160032, 1.92298529, 1.96094698]],

       [[1.88344735, 1.90706979, 1.33015663, 1.98471268, 1.02881393],
        [1.97152974, 1.50688605, 1.981655  , 1.86990314, 1.2078938 ],
        [1.41048346, 1.55964842, 1.33277885, 1.06417969, 1.18998765]]])

## 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.

In [54]:
#your code here
for x in range(len(d)):
    for y in range(len(d[x])):
        for z in range(len(d[x][y])):
            if d[x][y][z] > d_min and d[x][y][z] < d_mean:
                    f[x][y][z]= 25
            elif d[x][y][z] > d_mean and d[x][y][z] < d_max:
                    f[x][y][z]= 75
            elif d[x][y][z] == d_mean:
                    f[x][y][z] = 50
            elif d[x][y][z] == d_min:
                    f[x][y][z] = 0
            elif d[x][y][z] == d_max:
                    f[x][y][z] = 100
                    
print(x,y,z)

1 2 4


## 17. Print d and f. Do you have your expected f?

For instance, if your d is:

array ([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])
Your f should be:
array ([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],
       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])

In [40]:
#your code here


## 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 

("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],
       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])

Again, you don't need Numpy in this question.